spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://himanshu:7l4oCifHpsiRzJ2m@cluster0.xzypc.mongodb.net/?appName=Cluster0
      database: tickets
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: ticket-events